### ISSUE TITLE
Question about networking

### ISSUE THREAD

**Issue by felix-20** [aeronautical-informatics/apex-linux#140]
Dear DLR-team,

we are trying to connect an external application (outside of the hypervisor) with an a653rs partition. We found, that you implemented a `socket` feature. But we were unable to find an example on how to use them.
Could you please provide a small example?

Thank you in advance.

**Comment by sevenautumns** [comment]
Hello,

For the socket feature to work, you will need to activate the `socket`-feature for the `a653rs-linux`-crate used with the partition, which uses the socket. Then you can either use UDP or TCP ports.  
UDP only works for offering a UDP socket, external programs can send messages to.  
TCP only works for connecting to an external TCP socket.  
If you were to use TCP sockets, you would need to configure them in the config for the partition of your choice.
```yaml
major_frame: 1s
partitions:
  - id: 0
    name: Bar
    offset: 100ms
    duration: 10ms
    image: hello_part
    period: 1s
    sockets:
      - type: tcp
        address: 127.0.0.1:34256
```
Then at startup of the a653rs-linux hypervisor, the hypervisor would establish a TCP connection to `127.0.0.1:34256`.
In the Bar partition you could then obtain the TCP port via `a653rs_linux::partition::ApexLinuxPartition::get_tcp_stream("192.168.1.230:22")`

For UDP ports it works pretty much the same, with the difference that at startup the hypervisor would not try to establish an UDP connection to the given address, but try to bind a UDP socket for other programs to connect/send to.
